### ISSUE TITLE
[ENHANCEMENT] New MQTT Features

### ISSUE THREAD

**Issue by dbambus** [ESPWortuhr/Multilayout-ESP-Wordclock#106]
Laut @udo1toni:

> Den Versuch, ein passendes JSON Objekt zu senden, quittiert wie Wortuhr zwar mit einer Debug Meldung, die Anzeigt springt aber nicht entsprechend um. Nun ja, ist noch experimentell :)
> 
> Ein, zwei Gedanken zu mqtt:
> 
> Wünschenswert wären Eingabefelder für User, Passwort, ClientID und root Topic. Das root Topic sollte nicht mit einem Slash beginnen, das ist zwar möglich, aber allgemein in mqtt nicht erwünscht. Es ist wichtig, das root Topic frei setzen zu können (mindestens sollte es dem Hostname folgen), da man sonst nicht mehrere Wortuhren mit dem selben mqtt Broker unabhängig voneinander betreiben könnte.
> Es sollte unterhalb des Root topic mehrere Untertopics geben, z.B. set (das ergäbe z.B. Wortuhr/set als full Topic),
> Ein LastWillTopic wäre ebenso nützlich, damit können dann alle mqtt Teilnehmer erkennen, ob die Wortuhr Online oder Offline ist.
> 
> Da der Lauftext über den Effekt aktiviert werden kann, wäre es auch nett, den Lauftext über mqtt setzen zu können (sinnvollerweise ebenfalls über ein eigenes Topic). Der Client kann einfach alle Topics unterhalb des root Topic subscriben (mittels Wortuhr/#), unterschiedliche Topics tragen also bis auf den zusätzlichen Code für zusätzliche Funktionen nictht weiter auf.

Die MQTT Funktionen, sollten sinnvoll überdacht werden und erweitert werden. 

Vorbereitungen:

- Simplified Website Payload mit https://github.com/ESPWortuhr/Wortuhr/pull/105
- Umstellen des Website Payload auf ein JSON Format ist noch ausstehend

Action: 
- Implementierung des Payloadhandlings in MQTT analog zum JSON-Payload der Website, damit alle Features erreicht werden können.

**Comment by tali** [comment]
Wenn wir weiter an dem MQTT Support arbeiten wollen, dann sollten wir zuerst einmal ein Design-Dokument zu der gewünschten API erstellen (brauchen wir dann sowieso, am einfachsten als Markdown). Dann haben wir eine bessere Grundlage, um uns abzustimmen ohne immer viel Code ändern zu müssen. Wenn wir dann wissen, welche Topics unterstützt werden sollen und was die genau tun sollen, dann ist die Implementierung auch gleich viel leichter.
