### ISSUE TITLE
Version not being Updated via Gruntfile.js

### ISSUE THREAD

**Issue by dbambus** [ESPWortuhr/Multilayout-ESP-Wordclock#107]
Hallo @tali,

Ich wollte ein Release V2.6.1 bauen, aber wenn ich die VER in Uhr.h abändere, dann wird das nicht in Gruntfile berücksichtigt und die HTML nimmt weiterhin V2.6.0 an. 

Wo wird denn die Version noch definiert ? 

Mit freundlichen Grüßen
David

**Comment by tali** [comment]
Die Version für die Webseite kommt aus `package.json`.
Ist natürlich blöd, wenn es da mehrere Stellen gibt.
Eventuell können wir ja auch aus der `package.json` eine `version.h` oder so bauen, so dass wir nur noch eine Stelle haben.
