### ISSUE TITLE
.bin available? did they ever exist?

### ISSUE THREAD

**Issue by hurragithub** [ESPWortuhr/Multilayout-ESP-Wordclock#110]
Hi,

Sometime ago I downloadet a finished .bin here. don't they exist anymore or am I completely wrong?

thanks!

**Comment by dbambus** [comment]
Hey @hurragithub,

they still exist, just take a look under Releases: https://github.com/ESPWortuhr/Wortuhr/releases

Mit freundlichen Grüßen
David
