### ISSUE TITLE
LED-Matrix konfigurieren

### ISSUE THREAD

**Issue by 64608** [ESPWortuhr/Multilayout-ESP-Wordclock#117]
Hallo,

ich habe eine andere Reihenfolge der LEDs und diese in Version 2.5.1 auch erfolgreich konfiguriert. Jetzt wollte ich auf Version 2.6 upgraden allerdings gibt es jetzt hier diese Matrix nicht mehr in den Uhrtypes einstellungen? Kann mir da jemand evtl. sagen, wie ich trotzdem meinen Uhrtyp reinbekommen, so dass ach die Icons z.B. funktionieren?

Vielen Dank schonmal

	
Hier noch die Matrix, wie ich sie in Version 2.5.1 konfiguriert habe.

const uint8_t matrix[11][11] = {
            {109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99}, //     	ESKISTLFÜNF
            {88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98},           //		ZEHNZWANZIG	
            {87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77},           //		DREIVIERTEL
            {66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76},           //		TGNACHVORJM
            {65,  64,  63,  62,  61,  60,  59,  58,  57,  56,  55},         	 //		HALBXZWÖLFP
            {44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54},	         //		ZWEINSIEBEN
            {43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33},           //		KDREIRHFÜNF
            {22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32},	         //		ELFNEUNVIER
            {21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11},           //		WACHTZEHNRS
            {0,   1,   2,   3,   4,   5,   6,   7,   8,   9,   10},	                 //		BSECHSFMUHR
            {110, 111, 112, 113},

**Comment by dbambus** [comment]
Hallo @64608,

Entschuldige, dein Issue ist etwas untergegangen. Um Code auf dem Mikrocontroller einzusparen wurden die Uhrtypes abgeändert, um die Matrix nur beim Aufruf von `getFrontMatrix(uint8_t row, uint8_t col)` zu berechnen. Das spart sehr viele Konstanten ein. 

Zu deinem Code, mit diesem kleinen Override und der const Deklaration am Anfang einen Uhrtypes kann man zum "old" Style zurückkehren.


```
const uint16_t matrix[11][11] = {
    {109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99}, // ESKISTLFÜNF
    {88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98},           // ZEHNZWANZIG
    {87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77},           // DREIVIERTEL
    {66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76},           // TGNACHVORJM
    {65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55},           // HALBXZWÖLFP
    {44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54},           // ZWEINSIEBEN
    {43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33},           // KDREIRHFÜNF
    {22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32},           // ELFNEUNVIER
    {21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11},           // WACHTZEHNRS
    {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},                     // BSECHSFMUHR
    {110, 111, 112, 113},

    class UHR_114_t : public
    iUhrType{public :

                 virtual const uint16_t getFrontMatrix(uint8_t row, uint8_t col)
                     override{return matrix[row][col];
}
;

```
Der Rest der Header-datei müsste unverändert übernommen werden. 

Ich hoffe ich konnte es verständlich rüber bringen. Bei weiteren Fragen einfach melden. 

Mit freundlichen Grüßen
David
