### ISSUE TITLE
Frontplatte Vorlage

### ISSUE THREAD

**Issue by n3roGit** [ESPWortuhr/Multilayout-ESP-Wordclock#123]
Moin moin,

besteht die Möglichkeit eine CAD oder Fusion 360 Vorlage von euch zu erhalten? Das würde mir die Erstellung eines eigenen templates deutlich vereinfachen :D

**Comment by dbambus** [comment]
Moin moin, 

sorry, hat etwas gedauert. Ich habe Zugang zu einem LaserCutter hier am örtlichen Fablab, deswegen fertige ich die Fronten indem ich transparente Acrylplatten mit schwarzen Acryllack homogen ansprühe und dann mit dem LaserCutter die Buchstaben wieder freilege. Der Rest ist als gelagertes Stecksystem aus Pappelholz konzipiert, mit einer Schaumstoff Einlage (Plastazone) zur Selektion der Buchstaben.

Eine Fertigungsweise auf Basis von gefrästen Platten wäre cool, aber da habe ich keine Erfahrung. Möchtest du da vielleicht behilflich sein ?

Mit freundlichen Grüßen
David

**Comment by n3roGit** [comment]
Danke für die Antwort! Ich hab mittlerweile eine Vorlage und diese angepasst. Ich kann die gerne bereitstellen. Das würde sicher dem einen oder anderem helfen. Aktuell bin ich aber noch beim Bau. Wenn ich durch bin hab ich sicher einige schöne Fotos vom Bau für euch

**Comment by dbambus** [comment]
Hey, 

Sehr cool, freu mich, wenn es neue Bilder gibt.

**Comment by Eisbaeeer** [comment]
Falls Interesse besteht, kann ich meine DXF ebenfalls bereitstellen. Passend für WS2812B mit 60 LED´s / Meter. Gefräst wurde MDF Platte von vorne und hinten. Die Frontplatte wird mit Neodym Magneten befestigt (aufgeklebt auf Plexiglas Front).
Ist allerdings für die Version mit Wetteranzeige.

![20181222_161905](https://user-images.githubusercontent.com/4928271/144189460-23641227-5b4e-4818-a2fa-86dcbfad0d47.jpg)
![20181222_162011](https://user-images.githubusercontent.com/4928271/144189514-dc2bf072-d869-4327-a698-1ee2bbf78f28.jpg)

**Comment by n3roGit** [comment]
Hier sind meine Bilder :)
![UHR1](https://user-images.githubusercontent.com/8565847/148924102-b3531461-2bcb-4c0a-ba73-d7ad02a2c12a.jpg)
![bohren](https://user-images.githubusercontent.com/8565847/148924109-2eaa298d-6680-4df5-b53a-4f5e9875f031.jpg)
![bohren2](https://user-images.githubusercontent.com/8565847/148924118-61609602-cf47-4c6b-882b-1089bbaf97a5.jpg)
![IMG_20211113_134331](https://user-images.githubusercontent.com/8565847/148924143-d8a68daa-b0b6-4077-be12-74694419f3a1.jpg)
![IMG_20211113_134337](https://user-images.githubusercontent.com/8565847/148924443-3fe9fe94-9243-417a-bd92-4c523cd558b3.jpg)
![magnetfront](https://user-images.githubusercontent.com/8565847/148924648-bc65c3b0-fbab-4824-8034-a6e3fa4497a2.jpg)
![Funieren](https://user-images.githubusercontent.com/8565847/148924928-0e11ad86-3ceb-4fad-9827-fad9f1a62f1c.jpg)

Wichtig: Bei meiner Vorlage war das Wort "UHR" um eine Stelle weiter nach rechts gerückt. Ich musste die Vorlage in der Software dafür anpassen.

**Comment by dbambus** [comment]
Es sieht wirklich super aus :-)

Das ich die Bilder in das Repo mit aufnehmen ?

**Comment by n3roGit** [comment]
> Es sieht wirklich super aus :-)
> 
> Das ich die Bilder in das Repo mit aufnehmen ?

Klar =)


Falls benötigt schreibe ich gerne noch etwas dazu. Sag einfach bescheid!
