### ISSUE TITLE
Was für einen LDR verwenden? 

### ISSUE THREAD

**Issue by n3roGit** [ESPWortuhr/Multilayout-ESP-Wordclock#125]
Es gibt LDRs in vielen verschiedenen Versionen. Welchen sollte man hier nehmen?

**Comment by dbambus** [comment]
Hey @n3roGit 

eigentlich verwende ich die Standart LDRs von Aliexpress, keine besonderen. Ich hoffe das hilft, andernfalls messe ich mal nach.

Mit freundlichen Grüßen
David

**Comment by n3roGit** [comment]
Alles klar. Ich hab jetzt einfach "irgendeinen" aus meiner bastel kiste genommen und es funktioniert :)
