### ISSUE TITLE
Animation - bug

### ISSUE THREAD

**Issue by Eisbaeeer** [ESPWortuhr/Multilayout-ESP-Wordclock#131]
Hallo Leute
Ich habe heute mal die aktuelle Version vom Github compiliert. Sieht schon sehr gut aus. Bezüglich Animationen wollte ich Euer Wissen in Anspruch nehmen, da der Wetterbereich von mir mit den Animationen nicht so richtig klappt. Zum einen wird der Wetterbereich öfters innerhalb einer Minute aktualisiert bzw. umgeschaltet, was wohl mit den Animationen nicht fluchtet.
Jetzt die Frage, können wir das ändern?
Was muss ich triggern beim Wechsel der Anzeige, damit die Animation sauber durchläuft.
Ich habe mal zur Veranschaulichung zwei Videos gemacht, in denen man das Problem erkennt.
https://cloud.weimars.net/index.php/s/EgKneCfM7HCMrFx
Grüße Lars

**Comment by dbambus** [comment]
Hallo @Eisbaeeer,

das Issue ist jetzt relativ alt und ich habe hier keine Uhr zum testen. Besteht es denn weiterhin ? 

Mit freundlichen Grüßen
David

**Comment by Eisbaeeer** [comment]
Jep, es besteht weiterhin. Ich mache bei Gelegenheit ein Video davon.

**Comment by dbambus** [comment]
Müsste mit https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/346 gefixed sein.
