### ISSUE TITLE
Demo Mode - no exit - bug

### ISSUE THREAD

**Issue by Eisbaeeer** [ESPWortuhr/Multilayout-ESP-Wordclock#132]
Noch eine Kleinigkeit gefunden. Wenn man sich im Demo Mode befindet, kann man diesen nie wieder verlassen, außer man setzt die Seriennummer hoch.

**Comment by n3roGit** [comment]
Also ich nehme den Haken wieder raus und schwupps ist der aus

**Comment by Eisbaeeer** [comment]
Hast du einen reboot nach dem uncheck des Demo mode versucht?

**Comment by dbambus** [comment]
Gibt es denn mittlerweile einen neuerlichen Status zu diesem Issue?
