### ISSUE TITLE
Wortuhr hängt sich auf

### ISSUE THREAD

**Issue by n3roGit** [ESPWortuhr/Multilayout-ESP-Wordclock#136]
Hallo zusammen,

meine Uhr ist fertig und hängt mittlerweile an der Wand. Allerdings habe ich aktuell noch folgendes Problem.

Alle 1-2 Tage hängt sich die Uhr einfach auf und verbindet sich dann nicht mehr mit dem WLAN. Man kann dann nur das "Herz" sehen.
Ab und dann macht der ESP dann noch einen reboot und bekommt sich wieder ein. In der Regel bleibt die Uhr aber in diesem Zustand. 

Nachdem ich Sie Stromlos genommen habe ich neu verbinde geht alles wieder.

Aktuell kann ich das Problem noch nicht eingrenzen.

Habt ihr eine Idee?

**Comment by dbambus** [comment]
Hey @n3roGit,

ich werde das mal evaluieren, welche Version verwendest du ? Macht dein Router regelmäßig eine Zwangstrennung zum Provider, vielleicht bricht die Verbindung zum NTP server ab? 

Mit freundlichen Grüßen 
David

**Comment by n3roGit** [comment]
> Hey @n3roGit,
> 
> ich werde das mal evaluieren, welche Version verwendest du ? Macht dein Router regelmäßig eine Zwangstrennung zum Provider, vielleicht bricht die Verbindung zum NTP server ab?
> 
> Mit freundlichen Grüßen David

Dank dir!
Nein ich habe hier keine Zwangstrennung. Der NTP ist auch in diesem Fall mein PiHole. Dieser ist die ganze Zeit an.

Kann ich über den USB sonst die Serielle Konsole abgreifen? Würde das helfen?

**Comment by dbambus** [comment]
Hallo @n3roGit, 

Alles klar, ja ein Log würde helfen. Du kannst einfach über die Serielle Schnittstelle mit 115200 Baud/s loggen. Vielleicht bekommt man ja so Aufschluss über das Event. 

Mit freundlichen Grüßen
David

**Comment by n3roGit** [comment]
@dbambus 
Kann es sein, dass nach der Einrichtung die serielle Schnittstelle nicht mehr erreichbar ist?

Ich habe mir gerade ein testboard zusammen gebastelt. Nach der Verbindung mit dem Wifi komme ich da nicht mehr via Serial ran.

![image](https://user-images.githubusercontent.com/8565847/149121690-a8f6cb29-1f12-447e-9886-029505306d9b.png)
![image](https://user-images.githubusercontent.com/8565847/149121749-b6fb4de5-c88c-4a82-9784-1f0ee25ef214.png)

**Comment by n3roGit** [comment]
![image](https://user-images.githubusercontent.com/8565847/149121967-c05ad4f9-afa2-4c68-af1b-7d8953d2d496.png)
![image](https://user-images.githubusercontent.com/8565847/149121993-57e20c1e-30e3-4f10-b55f-311dedfbda03.png)


Sodele. Debug läuft. Mal abwarten, was passiert.

**Comment by n3roGit** [comment]
Hmm, mit meinem testaufbau hat bis jetzt alles funktioniert. Ich Bau die Tage die fertige Uhr nochmal auseinander und werde es dort loggen
