### ISSUE TITLE
downloadable bin-File

### ISSUE THREAD

**Issue by hurragithub** [ESPWortuhr/Multilayout-ESP-Wordclock#164]
hello, is the compiled bin-file available as a download? unfortunately i can't get the arduino-interface to work at all.

Thanks a lot!

**Comment by dbambus** [comment]
Hello @hurragithub,

with the newer releases we switched from Arduino to Plattform.io to get rid of the restrictions. The build guide will guide you step by step trough the building process. 

If you still find it to hard you can relate to the precompiled builds in https://github.com/ESPWortuhr/Wortuhr/releases

Cheers 
David
