### ISSUE TITLE
Connect WiFi manually in code

### ISSUE THREAD

**Issue by by-pm** [ESPWortuhr/Multilayout-ESP-Wordclock#174]
I was wondering how to connect to a wifi network manually in code.

I am making a clock for my classroom at work but somehow i cant connect to the wifisignal my clock is sending when i'm at work. Can someone help me to connect to the network of my work by using code?

**Comment by thoka** [comment]
Change https://github.com/ESPWortuhr/Wortuhr/blob/365863015e8ba5c3750aa80cb0dd93e2b03ed23a/src/Network.cpp#L31-L37
to 
```cpp
void Network_setup(const char *hostname) {
    wifiManager.setHostname(hostname);
    wifiManager.preloadWiFi("ssid","pwd");
    wifiManager.autoConnect(connectionSSID);
    // explicitly disable AP, esp defaults to STA+AP
    WiFi.enableAP(false);
    Network_info();
}
```

**Comment by dbambus** [comment]
Thank You @thoka

**Comment by by-pm** [comment]
Thank you @thoka. 

Does anyone know how to get the IP address once it's connected with the wifi by code. I dont have access to the router information. @thoka @dbambus

**Comment by dbambus** [comment]
Do you got serial access to the wordclock?

**Comment by dbambus** [comment]
Finally a new release V2.6.2. I have added the manual Wifi credential settings in the Wortuhr.cpp as a define ^^ @thoka
