### ISSUE TITLE
Funktionen Helligkeit und Geschwindigkeit

### ISSUE THREAD

**Issue by echo1483** [ESPWortuhr/Multilayout-ESP-Wordclock#214]
Hallo, mir ist aufgefallen das bei der 2.80 Version unter Funktionen die Regler Helligkeit und Geschwindigkeit fehlen. Ist das so gewollt??? LG Echo

**Comment by dbambus** [comment]
Hallo @echo1483, 

ich habe diesen Umstand auch schon bemerkt und ich habe dazu schon den Hinweis in https://github.com/ESPWortuhr/Wortuhr/pull/206 gegeben. Aber ich komme in nächster Zeit voraussichtlich nicht dazu das zu beheben. Vielleicht könnte @Wandmalfarbe da helfen? 

Mit freundlichen Grüßen
David
