### ISSUE TITLE
Animation colored letters/words

### ISSUE THREAD

**Issue by by-pm** [ESPWortuhr/Multilayout-ESP-Wordclock#239]
Hi,

I cloned the last version of the project and noticed the animation with colored letters or words doesnt work anymore. I dont know how to fix this but i thought i'll drop it here so someone can maybe look at it sometime. :)

**Comment by dbambus** [comment]
Hey @pienmatla,

thank you for the Bug notice, ill look into it :-). maybe you can work it out where it specifically fails in the code, by adding Serial.print("") to some lines of code to review where it happens ? :-) 

Cheers 
David

**Comment by dbambus** [comment]
It should work again :-)
