### ISSUE TITLE
[ENHANCEMENT] Sprachvariante im Backend wählen

### ISSUE THREAD

**Issue by michi1g** [ESPWortuhr/Multilayout-ESP-Wordclock#24]
viertel nach | viertel
viertel vor | dreiviertel
als Sprachvariante im Backend auswählbar machen

**Comment by dbambus** [comment]
Dazu gibt es von @tali schon einen Merge Request. ich werde das wahrscheinlich heute noch mergen. https://github.com/dbambus/Worduhr-v3/pull/32

**Comment by dbambus** [comment]
Feature ist nun vorhanden.
