### ISSUE TITLE
Take Timesettings form device

### ISSUE THREAD

**Issue by dbambus** [ESPWortuhr/Multilayout-ESP-Wordclock#240]
Hallo, 

aktuell besteht die Möglichkeit neben dem Timeserver oder einer Batterie RTC die Zeit auch manuell einzustellen. Das Menü dahinter ist allerdings nicht perfekt und es wäre eine coole Idee, wenn es auch die Möglichkeit gäbe die aktuelle Zeit des verwendeten Browsers zu übernehmen? 

Bzw. die aktuelle Zeitzone einstellbar zu machen, die ist ja aktuell hardcoded auf MEZ bzw. MESZ. 

Könntest du dir das ggf. mal anschauen ? @Wandmalfarbe 

Mit freundlichen Grüßen

**Comment by Wandmalfarbe** [comment]
Ich war im Übersetzungs-PR kurz davor, die manuelle Zeiteingabe zu überarbeiten, weil das bei den Übersetzungen kompliziert war. Ein [`<input type="time">` ist da das ideale HTML-Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time).

Könnte etwa so aussehen:

![Screenshot 2023-04-19 at 14-10-36 Word Clock](https://user-images.githubusercontent.com/17237627/233070822-373765e0-fa21-4f1f-be64-e6796e3fff4b.png)

Die automatisch eingetragene Zeit kann man ganz einfach aus dem Browser ermitteln, und man müsste nur noch speichern.

Die Zeitzone würde ich über ein Dropdown einstellen wollen. Da bin ich mir aber nicht so sicher, wie das dann ans Backend gesendet werden kann und dort empfangen wird. Könnte einen Prototyp bauen, der erstmal nur Frontend-Arbeiten enthält.

**Comment by dbambus** [comment]
Hallo @Wandmalfarbe,

dann machen wir das so, ich baue im Backend ein COMMAND Call für die Änderung der Zeitzone ein und sag dir welche werte ich erwarte und du könntest es dann im Frontend einbauen ? 

```Die automatisch eingetragene Zeit kann man ganz einfach aus dem Browser ermitteln, und man müsste nur noch speichern.```

Ich denke so wäre es am besten :-)

**Comment by dbambus** [comment]
First Issue solved with Pull https://github.com/ESPWortuhr/Wortuhr/pull/242, Thank you :-)

**Comment by melvinisken** [comment]
Ich hätte hier noch eine Ergänzung: Wäre es möglich, das Time-Setting auch direkt in das Setup-Menü einzubauen? Sprich, wenn die Uhr kein WLAN findet bzw. den eigenen AP offen hat, kann man sie quasi nicht benutzen. Es wäre super, wenn man dann zusätzlich zu den WLAN-Einstellungen einfach die Uhrzeit einstellen könnte und die Uhr direkt benutzen, auch ohne WLAN. Wenn dann irgendwann WLAN eingestellt wird, darf das dann wieder überschrieben werden, würde ich sagen. Ist natürlich auch weg, wenn der Strom weg ist, aber das wäre egal in so einem Fall (beim Herd muss ich nach nem Stromausfall die Uhr auch neu stellen :-) )

**Comment by dbambus** [comment]
Hallo @melvinisken, 

Das habe ich auch schon länger vor, anscheinend gibt es im WifiManager die Möglichkeit custom HTML einzubinden. Aber ich hatte bisher noch nicht genug Zeit mir das in Ruhe anzuschauen. Könntest du dazu ein neues Issue aufsetzen ? Sodass ich anhand des Titels ein Überblick habe ? 

Mit freundlichen Grüßen
David
