### ISSUE TITLE
[BUG] Leerzeichen im Lauftext werden nicht übernommen

### ISSUE THREAD

**Issue by michi1g** [ESPWortuhr/Multilayout-ESP-Wordclock#25]
Leerzeichen im Lauftext werden nicht in den Lauftext übernommen

**Comment by dbambus** [comment]
Hallo @michi1g, 

ich habe die Problematik in der neuen kommenden Version 2.5.0 gefixed. Es war das altbekannte Problem des Texthandlings, da er beim ersten Leerzeichen in Leserichtung die Nachricht in der Payload abschneidet. Ich hab das nun geändert. Er ließt jetzt in umgekehrter Richtung und schaut nach dem ersten Buchstaben. 

Ein möglicher Ansatz für die Zukunft wäre, die Payload der Website auf JSON umzustellen.
