### ISSUE TITLE
Initial setting of mode is broken

### ISSUE THREAD

**Issue by Wandmalfarbe** [ESPWortuhr/Multilayout-ESP-Wordclock#251]
When loading the page with a word clock in mode 3 (marquee) and navigating to functions, then the selected mode is wrong (word clock).

I made a mistake in [710adcfc9b7f234e4fa100d9c17905ee01c59c69651be46f1950593142052a9fR404](https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/238/files#diff-710adcfc9b7f234e4fa100d9c17905ee01c59c69651be46f1950593142052a9fR404)

Here is the diff for the fix.
``` diff
- $("#" + inputID).checked = true;
+ document.getElementById(inputID).checked = true;
```

**Comment by dbambus** [comment]
Thank You @Wandmalfarbe 

I uploaded the fix with ... https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/256
