### ISSUE TITLE
Mirroring Matrix only applied to WordClock

### ISSUE THREAD

**Issue by ThxAndBye** [ESPWortuhr/Multilayout-ESP-Wordclock#261]
When enabling to mirror the matrix then this is only applied to the WordClock and not to the other functionality like the WiFi symbol, IP-Address, etc. This makes the other features difficult to use when using a non-default LED matrix.

**Comment by dbambus** [comment]
Hey @ThxAndBye,

i will look into today.

**Comment by dbambus** [comment]
Hey @ThxAndBye, 

thanks for the bug report, I found the fault in the code. I just never applied the mirroring lines to the other modes of the clock. xD

It is fixed with https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/262
