### ISSUE TITLE
[ENHANCEMENT] Config datei erstellen und importierbar machen

### ISSUE THREAD

**Issue by michi1g** [ESPWortuhr/Multilayout-ESP-Wordclock#27]

**Comment by dbambus** [comment]
@ATho95 Hey, dieses Issue ist ja auch noch da, vielleicht könntest du ja deinen Code für die JSON-Format Uhrtype Config als Branch in deinem Fork teilen, weil dann könne ich mir das anschauen und eventuell auch auf dieses Issue adaptieren.
