### ISSUE TITLE
[BUG] Uhrzeit nach Sekundenanzeige falsch

### ISSUE THREAD

**Issue by michi1g** [ESPWortuhr/Multilayout-ESP-Wordclock#28]
Wenn man die Sekundenanzeige länger aktiviert lässt, wird nach dem Wechsel auf die Wortuhr Ansicht eine falsche Uhrzeit angezeigt

**Comment by dbambus** [comment]
Dieses Problem sollte mit den nötigen Änderungen an #31 auch gelöst werden.
