### ISSUE TITLE
[BUG] Lauftext Geschwindigkeit falsch herum

### ISSUE THREAD

**Issue by michi1g** [ESPWortuhr/Multilayout-ESP-Wordclock#29]
Die Geschwindigkeit vom Lauftext ist aktuell bei 0 = max und 40 = min. 
Durch den Slider von links(0) nach rechts(40) würde man erwarten, dass links langsam und rechts schneller ist

**Comment by dbambus** [comment]
Ich werde das mal abändern und auch die Geschwindigkeit eindeutiger Kennzeichen. In der Einheit 1 / Buchstabe pro Zeiteinheit.
