### ISSUE TITLE
Wordclock mit Pegelwandler

### ISSUE THREAD

**Issue by Erik1803** [ESPWortuhr/Multilayout-ESP-Wordclock#318]
Ich habe eine Wordclock mit LED-Streifen, die mittels Pegelwandler über den D6 Pin angeschlossen sind. Was muss ich anpassen, um diese anzusteuern?

**Comment by dbambus** [comment]
Hallo Erik, 

Die Neopixelbus-library, die ich verwende, erlaubt keine anderen Pins für den Datenbus der LED Stripes außer dem `RX` Pin. Ich weiß selbst wie nervig das ist, aber ich kann das selbst nicht umgehen. 

Mit freundlichen Grüßen
David

**Comment by Erik1803** [comment]
Hallo David,
danke für die schnelle Antwort! Das ist natürlich schade, aber trotzdem ein klasse Projekt!
Mit freundlichen Grüßen
Erik
