### ISSUE TITLE
Wifi Manager settings reset

### ISSUE THREAD

**Issue by irqnet** [ESPWortuhr/Multilayout-ESP-Wordclock#342]
Ist es möglich die Einstellungen komplett auf Werksreset zurück zu setzen ohne Zugriff auf die Webseite?

Ich habe das Problem das ich zwar eine IP aus meinem Heimnetz bekommen habe aber die Uhr nicht mehr erreichbar ist.

Bei tasmota oder ähnlichen esp Firmwares kann man glaube ich mit 5x power cycle den AP Mode starten?

**Comment by dbambus** [comment]
@irqnet 

Sowas in der Art habe ich bisher noch nicht implementiert. Aber das wäre etwas für die Zukunft. 

Mit freundlichen Grüßen
David

**Comment by irqnet** [comment]
Heißt in dem Fall hilft nur erase flash?

**Comment by dbambus** [comment]
Ja, leider schon.

**Comment by irqnet** [comment]
Da wären die Buttons von meinem SP511 Controller ja prädestiniert :)

**Comment by dbambus** [comment]
In der tat, das wäre auch super Leicht zu implementieren ^^ gerne mal ein Vorschlag machen ^^

**Comment by irqnet** [comment]
Ok meine Programmierskills halten sich für die Integration in Grenzen :) Aber ein erster Versuch, zumindest die Buttons einzubinden, noch ohne Code. Evtl. kann man includen abhäning von einer Variable? z.b. 

Controller=SP511E, WEMOS, NODEMCU etc.

Die Buttons gibts ja default mäßig bei einem Wemos/NodeMCU nicht, man könnte aber freie GPIOs definieren.

Für den SP511E sähe das aktuell so aus:

```c++
const int buttonPin1 = 2;
const int buttonPin2 = 13;
const int buttonPin3 = 14;

void setup() {
  
  Serial.begin(9600);


  pinMode(buttonPin1, INPUT_PULLUP);
  pinMode(buttonPin2, INPUT_PULLUP);
  pinMode(buttonPin3, INPUT_PULLUP);

}

void loop() {

  int buttonState1 = digitalRead(buttonPin1);
  int buttonState2 = digitalRead(buttonPin2);
  int buttonState3 = digitalRead(buttonPin3);



  if (buttonState1 == LOW) {
    Serial.println("Button POW pressed");
    delay(500);  // debounce delay
  }


  if (buttonState2 == LOW) {
    Serial.println("Button M pressed");
    delay(500);  // debounce delay
  }



  if (buttonState3 == LOW) {
    Serial.println("Button S pressed");
    delay(500);  // debounce delay
  }



}
```

**Comment by dbambus** [comment]
Hinzugefügt mit https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/394

**Comment by D-ominik** [comment]
Hi @dbambus, 
du hast es so umgesetzt, dass ein Reset der gespeicherten Daten erfolgt. Wenn ich @irqnet richtig verstehe, möchte er lediglich den AP-Mode (WifiManager-Portal) aktivieren möchte, oder?
