### ISSUE TITLE
16x18 Layout Fehler

### ISSUE THREAD

**Issue by Micha7719** [ESPWortuhr/Multilayout-ESP-Wordclock#356]
Hi, ab dem Release V3.1.0 zeigt die Digital Clock und die normale Wortuhr bei dem 16x18 Layout 
nur Kauderwelsch an.

Es fehlen dann Worte wie " Vor, Minuten...usw."

Bei 3.0 funktioniert es noch.

**Comment by dbambus** [comment]
Hallo @Micha7719,

das Problem liegt wohl daran, dass ich aktuell keine 24H Uhr hier habe, auf der Ich Debuggen. Ich werde mir mal was einfallen lassen wie ich das hinbekommen.  Das kann aber bis zum Wochenende Dauern. 

Mit freundlichen Grüßen
David

**Comment by Micha7719** [comment]
danke, die 3.0 zeigt nach ner Zeit genauso Kauderwelsch an :(

**Comment by merlin2k** [comment]
Schon irgendwelche Erkenntnisse woran es liegt?

lg

**Comment by dbambus** [comment]
Ich hab mir das mal angeschaut. Jupp es zeigt Mist an, zumindest wenn man sich nur das Frontarray ausgeben lässt :-) 

Hab grad gesehen von der Uhr gibt es verschiedene Betriebsmodi. 

https://rawgit.com/TorstenC/1a59b9c73730eb8e144d/raw/WC24h_18x16_Test.html

Ich werde jetzt erstmal Modi 1 implementieren, bin mir noch unsicher ob und wie ich die anderen sicher implementiere.

**Comment by merlin2k** [comment]
Modi 4 fände ich besser;)
Modi 1 hat ja nur 12h

trotzdem schon mal vielen Dank

**Comment by dbambus** [comment]
Okay, dann mache ich Modi 4 fürs erste :-)

**Comment by dbambus** [comment]
Ich habe mal einen Pull Request mit den Änderungen für die 16x18 Wordclock erstellt und gemerged, könntet Ihr den stellen Stand mal testen ? 

Es war doch einiges zu tun um das gangbar zu bekommen :-) 

https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/366

**Comment by Micha7719** [comment]
danke, die aktuelle Uhrzeit sieht schon mal gut aus. Muss man mal beobachten wie es sich den ganzen Tag verhält. 
Was schon mal nicht funktioniert ist:  " Es ist " kann man nicht mehr ausschalten. Die Funktion hat keinen Effekt.

Ich hoffe es ist auch noch irgendwann möglich die anderen Modis einzubauen und dazwischen  zu wechseln:)

**Comment by dbambus** [comment]
Mit https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/367 kommt der Fix für das "Es Ist". Hatte da anscheinend ein `Break;` vergessen.

**Comment by Micha7719** [comment]
perfekt, funktioniert:) wenn jetzt noch irgendwann die andern Modis dazu kommen ist sie perfekt.
Die Uhrzeit sieht bisher auch fehlerfrei aus.
Ein Glück hatte ich nicht den Bau der 16x18 aus dem microcontroller Forum angefangen. Das wäre einiges mehr an Arbeit und Teilen geworden.

Vielen Danke für die tolle Arbeit!
