### ISSUE TITLE
11x11 V3 Fehlt im Gui

### ISSUE THREAD

**Issue by Heiliger-Gral** [ESPWortuhr/Multilayout-ESP-Wordclock#360]
Hi hab mir die Uhr die ich in Groß bauen möchte mal in klein gebaut und Festgestellt das in der WebGUI die Version 11x11v3 fehlt und natürlich hab ich genau die version ;) 

Auch hier wird die Minuten Anzeige in der Letzten Zeile und nicht ganz unten bzw in den Ecken dargestellt 

die "DE11x11.v3.hpp" scheint ja vorhanden zu sein

**Comment by dbambus** [comment]
Hallo @Heiliger-Gral,

diese version sollte als "🇩🇪 11 × 11 (panbachi)" in der GUI auftreten, oder ?

Mit freundlichen Grüßen
David

**Comment by Heiliger-Gral** [comment]
@dbambus 

Die Version ist da und sieht gerade recht gut aus , war aber vor ner stunde noch etwas komisch ich beobachte das mal ...und die  LED´s in den Ecken da nimmt er die ersten 4 der letzten reihe 

MFG

**Comment by AngeloMontesano** [comment]
Du musst in /include/Uhrtypes/DE11x11.hpp  , in   folgenden abschnitt    Zeile 51.    " case 2: // LEDs für "Corners" type minute display, 
folgende änderung machen:
Alt:                returnArr[i] = 110 + i;
Neu:                returnArr[i] = 121 + i;

**Comment by AngeloMontesano** [comment]
In include/Uhrtypes/DE11x11.hpp.  fehlt ein break.  Nach Zeile 113. " v_vor. 
        case FrontWord::v_vor:
            setFrontMatrixWord(3, 2, 4);
        break;

**Comment by dbambus** [comment]
Hey @AngeloMontesano, 

Danke für den Fix in DE11x11.hpp, da muss tatsächlich ein 121 rein. Mache doch gerne einen Pull Request dafür, dann kann ich das Mergen :-)

Zum zweiten Kommentar, beide "vor" sind das gleiche Wort. Nur das "v_vor" wird nur in der 11x11v2 bzw. 16x18 separat verwendet. Es ist das "Vor" nach dem "Viertel". Bei allen anderen Uhrentypen ist keine separate Deklaration notwendig und durch das Weglassen des "break;" spart man sich die 3 Zeilen Code, die sonst bei allen anderen Uhrentypen anfallen würden. 

Analog dazu gibt es auch eine Kombination "nach/v_nach" einige Zeilen vorher.  

Mit freundlichen Grüßen
David
