### ISSUE TITLE
Compile error Wifi Manager

### ISSUE THREAD

**Issue by Eisbaeeer** [ESPWortuhr/Multilayout-ESP-Wordclock#37]
Hi
Get compile error regarding wifi-manager.
Arduino version 1.8.14

`

WARNUNG: Bibliothek Timezone behauptet auf avr Architektur(en) ausgeführt werden zu können und ist möglicherweise inkompatibel mit Ihrem derzeitigen Board, welches auf esp8266 Architektur(en) ausgeführt wird.
In file included from sketch\Network.cpp:8:0:

WiFiManager::getRSSIasQuality(int)' is private
     int           getRSSIasQuality(int RSSI);
                   ^
Network.cpp:20:42: error: within this context
  return wifiManager.getRSSIasQuality(rssi);
                                          ^
sketch\Network.cpp: In function 'void Network_disable()':
Network.cpp:24:14: error: 'class WiFiManager' has no member named 'disconnect'
  wifiManager.disconnect();
              ^
sketch\Network.cpp: In function 'void Network_reboot()':
Network.cpp:28:14: error: 'class WiFiManager' has no member named 'reboot'
  wifiManager.reboot();
              ^
sketch\Network.cpp: In function 'void Network_resetSettings()':
Network.cpp:33:14: error: 'class WiFiManager' has no member named 'reboot'
  wifiManager.reboot();
              ^
sketch\Network.cpp: In function 'String Network_getSSID()':
Network.cpp:37:21: error: 'class WiFiManager' has no member named 'getWiFiSSID'
  return wifiManager.getWiFiSSID();
                     ^
sketch\Network.cpp: In function 'void Network_setup(const char*)':
Network.cpp:41:14: error: 'class WiFiManager' has no member named 'setHostname'
  wifiManager.setHostname(hostname);
              ^
sketch\Network.cpp: In function 'void Network_loop()':
Network.cpp:47:14: error: 'class WiFiManager' has no member named 'process'
  wifiManager.process();
              ^
C:\Users\Lars Weimar\OneDrive\Dokumente\Arduino\Wortuhrv3\Wortuhrv3.ino: In function 'void setup()':
Wortuhrv3:359:14: error: 'class PubSubClient' has no member named 'setServer'
   mqttClient.setServer(G.MQTT_Server, G.MQTT_Port);
              ^
Wortuhrv3:360:14: error: 'class PubSubClient' has no member named 'setCallback'
   mqttClient.setCallback(MQTT_callback);
              ^
exit status 1
within this context
`

**Comment by Eisbaeeer** [comment]
Version 2.5 compiles without errors ;-)

**Comment by dbambus** [comment]
Hey Eisbeeer,

japp, die V2.6.0 ist noch immer in der Entwicklung und verlässt sich auf Funktionen der DEV Branch von tzapu/WifiManager. Diese Version von WifiManager hat noch kein Offizielles Release ;-). 

Die V2.5.0 ist soweit Stabil, daher einfach die Version verwenden.

**Comment by Eisbaeeer** [comment]
Ja das kann ich bestätigen. Die Version 2.5 ist stable und läuft bei mir jetzt schon einige Tage durch (auch mit Openweathermap). Ich schließe dann das issue.
