### ISSUE TITLE
Symbol ändern

### ISSUE THREAD

**Issue by mrschloemp** [ESPWortuhr/Multilayout-ESP-Wordclock#382]
Moin, 
anfängerfrage.
Hab die Uhr nachgebaut und jetzt mal ein Update gemacht.
In den Funktionen der Uhr ist jetzt auch Icon enthalten und standartmäßig ein Herz.
Ich finde das Symbol nicht im Source-Zip und wüsste auch nicht wie man das aktualisieren kann. 
Gibt´s dazu ein HowTo?

Danke

**Comment by dbambus** [comment]
Hallo @mrschloemp, 

vielleicht kann nicht da an diesen Post verweisen. https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/issues/331

Ich habe aktuell nur ein paar Symbole implementiert, auch durch die Hilfe anderer :-). Für diese gibt es allerdings kein Auswahlmenü, das soll man in einer späteren Version kommen. 

Mit freundlichen Grüßen
David

**Comment by mrschloemp** [comment]
Die Antwort kam echt flott. Danke
Richtig nice wäre wenn man auch eigene Symbole hochladen könnte.

Dann warte ich jetzt gespannt auf die kommenden Releases.
Danke

**Comment by dbambus** [comment]
Hehe, 

in der Zwischenzeit kannst du ja in https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/blob/main/include/icons.h deine eigenen Symbole hinzufügen und in der `ClockWork: :displaySymbols(uint8_t iconNum)` entsprechend anpassen ^^

Mit freundlichen Grüßen
David

**Comment by mrschloemp** [comment]
Mal so auf die schnelle erstellte Symbole E-Mail, Glocke/Klingel, Stop bzw. X und Standby Symbol.
Am Anfang jeden Symbols die 0b000... habe ich verändert, sollte aber überprüft werden.
[own_symbol.txt](https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/files/14721972/own_symbol.txt)

**Comment by dbambus** [comment]
hallo @mrschloemp 

Das sieht doch soweit ganz gut aus :-) Ich werde das mal für den nächsten Push übernehmen.

Mit freundlichen Grüßen
David

**Comment by mrschloemp** [comment]
Werde noch ein paar mehr erstellen und bei Gelegenheit hier hochladen.

**Comment by dbambus** [comment]
Hallo @mrschloemp,

ich werde die aktuellen Symbole von dir in den Kommenden Stand übernehmen und versuchen eine Art Auswahlmenü zu bauen für die Symbole :-) 

Kommt noch was ? oder kann ich fürs erste das Issue schließen ? 

Mit freundlichen Grüßen
David

**Comment by mrschloemp** [comment]
Für den jetzigen Moment kommt nichts. 
Wenn ich noch welche mache, kann ich das hier ja wieder reinsetzen.

**Comment by mrschloemp** [comment]
Das dauert noch ein bisschen

**Comment by dbambus** [comment]
Alles klar :-) dann Close ich das Issue erstmal dann habe ich die Übersicht. Man kann es ja dann erneut öffnen.
