### ISSUE TITLE
Fehler beim Kompilieren in PlatformIO

### ISSUE THREAD

**Issue by Pauli29** [ESPWortuhr/Multilayout-ESP-Wordclock#389]
Mehrere "unexpected ')' before '[' "
Was mache ich da falsch?
Habe am Code nichts geändert 

`.pio\libdeps\nodemcuv2\NeoPixelBus\src/internal/methods/NeoEsp8266UartMethod.h:380:30: error: expected unqualified-id before '[' token`

**Comment by dbambus** [comment]
Hallo @Pauli29,

es kann sein, dass sich paar libs aktualisiert haben und ich die entsprechend anpassen muss. Ich bin aber aktuell im Urlaub und kann nur am Handy antworten. Bitte hab noch etwas Geduld.

Mit freundlichen Grüßen
David

**Comment by dbambus** [comment]
Hallo @Pauli29,

ich habe es mittlerweile kontrolliert. Bei mir geht es mit dem aktuellen Stand der Website zu kompilieren :-) selbst mit der neuen Version 2.7.9 der Neopixelbus library.

kannst du mal einen git pull machen ? oder Platformio clean ?

Mit freundlichen Grüßen
David

**Comment by Pauli29** [comment]
Hallo!

Ich habe vorerst die fertige Bin geflashed aber ich werde es zeitnah testen und eine Rückmeldung geben.


Jedoch bringe ich mqtt nicht zum Laufen :-(

Die eingegebenen sind definitiv richtig aber der Broker und somit auch Homeassistent empfangen nichts.

Was mache ich da falsch?


Beste Grüße

Paul Reinhart
________________________________
Von: David Panusch ***@***.***>
Gesendet: Donnerstag, 18. April 2024 16:15
An: ESPWortuhr/Multilayout-ESP-Wordclock
Cc: Pauli29; Mention
Betreff: Re: [ESPWortuhr/Multilayout-ESP-Wordclock] Fehler beim Kompilieren in PlatformIO (Issue #389) 

Hallo @Pauli29,

ich habe es mittlerweile kontrolliert. Bei mir geht es mit dem aktuellen Stand der Website zu kompilieren :-) selbst mit der neuen Version 2.7.9 der Neopixelbus library.

kannst du mal einen git pull machen ? oder Platformio clean ?

Mit freundlichen Grüßen
David

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/issues/389#issuecomment-2063977961", "url": "https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/issues/389#issuecomment-2063977961", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by udo1toni** [comment]
In der Version 3.2 bekommt der Broker keinerlei Lebenszeichen über Topics (ist aber in der V3.3 schon drin)
Um zu prüfen, ob der Kontakt da ist, kannst Du das Logging für Mosquitto auf `all` setzen und den Dienst neu starten, dann muss es einmal pro Sekunde ein Request geben.
Alternativ kannst Du versuchen, einen Effekt einzuschalten, Z.B. mit Topic wordclock:
`mosquitto_pub -h 192.168.178.55 -t wordclock/cmd -m '{"effect":"Rainbow"}'`
Ohne Gewähr, ich nutze immer MQTT Explorer, zumindest Topic und JSON sollten aber korrekt sein. Die IP ist natürlich die Deines MQTT Brokers...

**Comment by dbambus** [comment]
Da sich hier in der Issue schon länger nichts mehr getan hat, gehe ich jetzt mal davon aus, dass das Problem gelöst worden ist.
