### ISSUE TITLE
[v3.3] Minutenanzeige ohne Funktion

### ISSUE THREAD

**Issue by udo1toni** [ESPWortuhr/Multilayout-ESP-Wordclock#395]
In der aktuellen Version (main, [3fdb476] ?) ist die Minutenanzeige ohne Funktion, das heißt, Die Uhr verhält sich so, als sei in der Weboberfläche "Minuten Anzeigemodus Aus" gewählt. 
Schaltet man den Anzeigemodus einmal hin und zurück, so wird die Anzeige aktualisiert, bleibt dann aber so lange erhalten, bis wieder volle fünf Minuten errreicht werden (und damit die Minutenpunkte korrekterweise alle erlöschen).

**Comment by dbambus** [comment]
Hey Udo, 

danke für den Issue :-) ich habe den Fix dazu jetzt im Pull request https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/396

Letztlich hat ein Switchcase gefehlt.

Mit freundlichen Grüßen
David
