### ISSUE TITLE
PlatformIO

### ISSUE THREAD

**Issue by ruebraun** [ESPWortuhr/Multilayout-ESP-Wordclock#414]
Ich erhalte folgende Fehlermeldung:

npm ci install
Der Befehl "npm" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Archiving .pio\build\d1_mini_pro\libff1\libSPI.a
*** [node_modules\.package-lock.json] Error 1
======================================= [FAILED] Took 3.08 seconds =======================================

**Comment by dbambus** [comment]
Hallo @ruebraun, 

hat sich denn das Problem in der Zwischenzeit gelöst ? Hast du denn rpm installiert ? 

beispielsweise mit dem Befehl 
`sudo apt install npm`

Mit freundlichen Grüßen
David
