### ISSUE TITLE
Minute LED not working

### ISSUE THREAD

**Issue by commandermatz** [ESPWortuhr/Multilayout-ESP-Wordclock#419]
Trying to use the 4 minute LED Version
On startup, they are also not available.
Do I have to activate it somewhere in the code?

**Comment by dbambus** [comment]
Hello,

Any configuration of the word clock can also be done from the hosted website. Just go to the Settings ribbon and change the Minutes layout there.

Cheers 
DAVID

**Comment by commandermatz** [comment]
Sorry...
those 4 LEDs were either not soldered correctly or are just dead. I changed them an et voila: works.

File is closed.
