### ISSUE TITLE
Installation auf ESP32

### ISSUE THREAD

**Issue by Somaxax** [ESPWortuhr/Multilayout-ESP-Wordclock#421]
Hallo, ist es möglich das ganze auch auf einem ESP32 zu installieren? Ich habe das probiert, aber es scheint mit dem ESP32 ein Problem zu haben. Was müsste ich tun, damit es darauf funktioniert?

**Comment by dbambus** [comment]
Dopplung zu https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/issues/328 

Ich werde mich darum kümmern, aber erst will ich die Version abschließen und dann mal einen Port wagen.
