### ISSUE TITLE
Colorjumps for all words on minute change

### ISSUE THREAD

**Issue by RoHA1965** [ESPWortuhr/Multilayout-ESP-Wordclock#423]
CLOSE this. Seems to be a issue on my side :-(
In an ealier version (cannot remember which one) are the minute points also fading through the colors, and the minute change did not make a color jump on all words. I cannot find the version where this early functionality are working.
In the current version the minute LEDs are stable on the color pointed on the color selection.
Did anyone have the same colorjumps each minute. 
Setup: colored words, fade, duration short. Mode: Wordclock.

**Comment by dbambus** [comment]
Hey @RoHA1965 

its closed now, but thanks anyway for reaching out. 

Cheers David
