### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by pfefferle** [ESPWortuhr/Multilayout-ESP-Wordclock#424]
@dbambus kannst du vielleicht eine neue Version releasen?

Ich habe selbst versucht das Projekt zu bauen, es hat aber leider nicht geklappt :(

**Comment by dbambus** [comment]
Hey @pfefferle, 

Ich habe mal eine Pre-release Version hochgeladen. https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/releases/tag/V3.3_Beta

Ich bitte gerne um Bug reports :-) 

Mit freundlichen Grüßen
David
