### ISSUE TITLE
Wetteranzeige

### ISSUE THREAD

**Issue by MVarious** [ESPWortuhr/Multilayout-ESP-Wordclock#425]
Hallo, zu erst ein Dankeschön für dieses tolle Projekt.
Ich wollte mir nun die Variante mit dem Wetter bauen, doch leider bin ich auf ein paar Probleme gestoßen.

Hat jemand schon mal solch eine Uhr zum laufe bekommen. Ich wäre sehr daran interessiert was ich falsch gemacht habe.
Bei der normalen Uhr ist es kein Problem 4 Leds unten für die Sekunden einzusetzen..
Bei der WetterVariante fängt es dann leider an zu spinnen. auch die Einstellmöglichkeiten in dem Webinterface helfen nicht. 

Momentan "fehlen mir" 3 leds.. damit ich auch noch zum Ende das °C angezeigt bekomme.. Scheinbar funst alles bist auf die letzten beiden Zeilen. das Wort ZWANZIG ist zu kurz "beleuchtet" und damit ist das DREIßIG verschoben und das °C ist nicht mehr auf dem Raster. 

Ich wäre über ein paar tipps sehr dankbar

Liebe Gruß
Michael

**Comment by dbambus** [comment]
Hey @MVarious,

mich schaue mir morgen mal das Problem genauer an ;-) aber kannst du mal ein Foto der Uhr machen ? Wie viele LEDs sind für die Word Matrix da, die Sekunden und die Wettermatrix ?

Mit freundlichen Grüßen
David

**Comment by MVarious** [comment]
Hallo, klasse für die schnelle nachricht.. Ich habe in der Zwischzeit verschiedene Versionen durchgetestet.. aber bei allen scheinbar der gleich fehler.. was mir auch aufgefallen ist, das wenn ich die Wetter API eingebe.. sie nach dem Seitenrefresh nicht mehr sichtbar ist.. Ist das nur Datensicherheit oder ein Fehler?
Bilder sehen so aus. also die Uhr oben klappt prima. die letzten 2 Zeilen machen mir Sorgen.
Und wie gesagt.. egal was er anzeigt,, das °C fehlt immer.. hänge ich jedoch an die letzte Led noch welche dran, scheint das angezeigt zu werden nur irgendwie nach hinten raus geschoben.
Achja und ich nutzt WS2815 ( auf 12V) ich denke das sollte keinen großen unterschied machen. Da das Uhrensegment sehr gut funktioniert.
Eine Besonderheit ist das sobald man auf den Wetterskin wechselt, das wort UHR immer leuchtet, was es ja eigentlich nur zur vollen Stunde tut

Danke fürs anschauen
![dreißig](https://github.com/user-attachments/assets/860ee67c-8e42-4f57-a6ae-83f351511b86)
![zwanzig](https://github.com/user-attachments/assets/1d90b3f9-389c-470d-873a-45fd7a9f3462)
![komisch](https://github.com/user-attachments/assets/2a47fdb6-41e3-44d5-958f-95abb73b62a2)

**Comment by dbambus** [comment]
Hey, 

ich hab das grad überprüft und mir paar Haare rausgerissen. Es fehlt eine Zeile von Buchstaben. Ich habe das mal in dem Commit hinzugefügt. 

https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/compare/main...dbambus:Wortuhr:main 

Ich habe selbst diese Uhr nie gebaut, deswegen ist mir der Fehler nicht aufgefallen. 

Mit freundlichen Grüßen
David

**Comment by MVarious** [comment]
Hallo an die Runde
Ich habe im Chancelog von der Beta 3.3 nicht rauslesen können, das es eine Änderung für das Wetterproblem gab, habe sie dennoch aufgespielt und leider sind die Probleme mit dem verschobenen zwanzig und dreißig weiterhin vorhanden. Und weiterhin sind die LEDs die das ° Symbol abdecken aus der Matrix "rausgeschoben" wenn man an die letzte Led der Matrix noch weitere LEDs dranbaut sieht man diese dann leuchten. Beste Grüße Micha

**Comment by MVarious** [comment]
Hallo, Ich habe eben die neuste Beta auf meiner Wort/Wetter Uhr aufgespielt.. Die Überarbeitung des Webinterface sieht klasse aus. Leider bleiben die Probleme mit den letzten Zeilen bestehen.. Das Wort ZWANZIG ist verschoben und °C ist weiterhin außerhalb der Matrix. Das Wort Zwanzig wird nach einigen Sekunden mit etwas anderem ausgetauscht was für mich erstmal keinen Sinn macht. Ich habe die Uhr im Regenbogen und allen anderen Effekten laufen lassen. Dort sind alle LEDs korrekt an...
Das Wort NULL ist wohl auch um eine Stelle verrückt

Hier ein Video 

https://github.com/user-attachments/assets/de959d62-e6aa-4c93-805c-c72eedceaf77
