### ISSUE TITLE
Colored words and letters animation won't work in Dutch

### ISSUE THREAD

**Issue by by-pm** [ESPWortuhr/Multilayout-ESP-Wordclock#430]

**Comment by dbambus** [comment]
The big question is why xD

Have you restarted the wordclock after the settings ?

**Comment by dbambus** [comment]
@pienmatla Have you tested the new Pre Release ? 

https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/releases/tag/V3.3_Beta

**Comment by by-pm** [comment]
@dbambus yes i did try it. isnt working yet 🫠

**Comment by dbambus** [comment]
It seems to work, but you have to have a transition activated aswell. 

It is not working without any.

**Comment by dbambus** [comment]
Hey @pienmatla,

is it working with transitions on even in Dutch ? 

Cheers 
David
