### ISSUE TITLE
[3.3 ff] Auswahl des Matrix Effekts führt zu Boot-Loop

### ISSUE THREAD

**Issue by udo1toni** [ESPWortuhr/Multilayout-ESP-Wordclock#432]
Das aktuelle Build (ebenso die Beta) hat den Fehler, dass bei´Auswahl des Matrix Effekts der Microcontroller unmittelbar neu bootet.
Anschließend muss das Device neu geflasht werden, weil vor Erreichen des Webservers der Code erneut abstürzt.

**Comment by dbambus** [comment]
Gefilde mit https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/439/commits/e6fa4267f7e41820715856c7f5cd0e4a219ca9da

Vielen Dank für euren Bugreport @udo1toni und @D-ominik
