### ISSUE TITLE
Lauftext enthält unerwünschtes Zeichen

### ISSUE THREAD

**Issue by D-ominik** [ESPWortuhr/Multilayout-ESP-Wordclock#433]
In der aktuellen Codeversion wird an den eingegebenen Lauftext eine Null statt eines Leerzeichens angehängt. Beim standardmäßigen "Hello World" besteht das Problem nicht.

**Comment by dbambus** [comment]
Hey @D-ominik, 

vielen Dank für den Bugreport. Wurde mit https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/439/commits/fc2546bee4ce0fc88761a44f91647596b1bd9e8d gefixed
