### ISSUE TITLE
Animationsauswahl führt zu fehlerhafter Darstellung

### ISSUE THREAD

**Issue by D-ominik** [ESPWortuhr/Multilayout-ESP-Wordclock#434]
In der aktuellen Codeversion UND einer neu geflashten Firmware führt das Auswählen der Animation "Überblenden" oder Auswahl der Dauer "kurz" zu einer fehlerhaften Darstellung. Außerdem ändert sich die Farbe etwas.

Nach etwas hin- und herwechseln zwischen anderen Animationen kommt wieder die korrekte Anzeige und auch beim Wechsel zu "Überblenden" besteht dann kein Problem mehr.

**Comment by dbambus** [comment]
Hey @D-ominik, 

Ich habe etwas hin und her probiert, aber ich kann den Fehler nicht reproduzieren. Was ist allerdings sehe, ist das der LED streifen echt schlecht zwischen Pink an uns ausfaden kann. Hier kommt es zu einer art flickern, dass kann ich allerdings nicht verbessern. 

Mit freundlichen Grüßen
David
