### ISSUE TITLE
IP nicht erreichbar

### ISSUE THREAD

**Issue by ghost** [ESPWortuhr/Multilayout-ESP-Wordclock#438]
Hallo zusammen,
ich habe (leider) keine Ahnung von irgendeiner Programmierung, habe aber erfolgreich die Software auf einen ESP8266 überspielt bekommen.
Die Uhr funktionierte einwandfrei, es liessen sich auch alle Funktionen abrufen...
Als ich dann später noch einmal in den Funktionen spielte, sprang die Uhr in den "Bootmodus" wo die IP Adresse angezeigt wird und ist unter der IP nicht mehr erreichbar. Im WLAN Netz ist sie angemeldet. Aus diesem Modus komme ich nicht mehr hinaus.
Das ist mit an zwei verschiedenen Uhren absolut gleich so passiert.
Jetzt habe ich leider ein großes Fragezeichen im Gesicht, da auch eine Neuprogrammierung der Software leider keine Abhilfe geschaffen hat. Ich frage mich, ob es vielleicht an meinen ESP8266 der Fa. AZ-Delivery liegen kann, da ich da schon die ein oder andere Beschwerde wegen der Qualität gehört habe...
Vielleicht kann mir ja jemand helfen.
Ansonsten ein Riesen Dankeschön für das veröffentlichen der Software; es hat Riesenspaß gemacht die Uhr zu bauen und die tollen Funktionen zu testen.
Danke für Eure Mühe!!

**Comment by dbambus** [comment]
Hallo @Tanterolf,

Es sollte nicht am Hersteller der Uhr liegen. Da habe ich schon viele Produkte ausprobiert. Ich würde mal vermuten, dass es am eingestellten NTP Server liegt. Vielleicht kannst du ja im Webmenü einen anderen einstellen. 

Mit freundlichen Grüßen
David
