### ISSUE TITLE
TransitionFire geht nicht mehr

### ISSUE THREAD

**Issue by RoHA1965** [ESPWortuhr/Multilayout-ESP-Wordclock#454]
Fire geht nicht.
Anzeige Deutsch 10x11.
Es wird nur ein einiger Punkt beim "Bodenstart" angezeigt FIRE_1 und sonst nicht mehr.

**Comment by dbambus** [comment]
Fix with https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/pull/457
