### ISSUE TITLE
Minuten Punkte anpassen

### ISSUE THREAD

**Issue by fs-sw** [ESPWortuhr/Multilayout-ESP-Wordclock#473]
Hallo,
leider finde ich nicht, wo ich die Minuten Punkte anpassen kann.
Bei meiner Uhr ist es eine 11 x 11 Matrix und in der Zeile 11, also x sind es die Punkte 3 5 7 9 welche die Minuten anzeigen sollen.
Wer kann mir helfen?
Vielen Dank
P.S. Ich habe eine Version in Kölner Sprache daraus gemacht.

**Comment by dbambus** [comment]
Hey @fs-sw,

Gruß nach Köln aus Erlangen. 

In ein Uhrtypen stehen alle Definitionen drinnen. Zum Beispiel hier: https://github.com/ESPWortuhr/Multilayout-ESP-Wordclock/blob/main/include/Uhrtypes/DE11x11.hpp 

Hier drinnen gibt es die `overwrite` Funktion: 

```
virtual const void getMinuteArray(uint16_t *returnArr, uint8_t col) override {

        uint16_t numPixelsWordMatrix = rowsWordMatrix() * colsWordMatrix();

        if (G.buildTypeDef == BuildTypeDef::DoubleResM1) {
            numPixelsWordMatrix = rowsWordMatrix() * (colsWordMatrix() * 2 - 1);
        }

        for (uint8_t i = 0; i < 4; i++) {
            switch (col) {
            case 0: // LEDs for "LED4x" minute display
                returnArr[i] = numPixelsWordMatrix - (7 - i);
                break;

            case 1: // LEDs for "LED7x" minute display
                returnArr[i] = numPixelsWordMatrix - (7 - (i * 2));
                break;

            case 2: // LEDs für "Corners" type minute display
                returnArr[i] = numPixelsWordMatrix + i;
                break;

            default:
                break;
            }
        }
    };
```

In der sind die Minutenarray für verschiedene Bauarten definiert. Diese Funktion muss angepasst werden ganz gleich in welchem Layout, einfach dort einfügen, wenn noch nicht vorhanden und mit `overwrite` kennzeichnen, so dass diese Funktion in der .hpp übernommen werden soll. 

`returnArr[i] = numPixelsWordMatrix - (7 - i);` Diese zeile code gibt ein Wert zurück, nämlich ein Array bestehend aus vier Nummern, z.B. [ 125, 126, 127, 128] entsprechend für 4 LEDs. 

Für deine Uhr solltest du also [1,2,3,4] mit deinen LED Zahlen anpassen und in die Uhrtype einfügen: 

```
virtual const void getMinuteArray(uint16_t *returnArr, uint8_t col) override {
                returnArr[i] = [1,2,3,4];
    };
```

Ich hoffe das konnte helfen. 

Mit freundlichen Grüßen
David

**Comment by fs-sw** [comment]
Danke für die schnelle Antwort. 
Leider verstehe ich es noch nicht ganz.
In der Version, die ich angepasst habe (DE11x11v2) gibt es diese Zeile nicht. Muss ich die einfügen?
Danke für die Hilfe

**Comment by dbambus** [comment]
Hey, 

genau, da einfach einfügen :-) 

Mit freundlichen Grüßen
David

**Comment by fs-sw** [comment]
So?

 *  X  | W x S x F x N x U H R 
 */

class De11x11V2_t : public De11x11_t {
public:

    virtual const void getMinuteArray(uint16_t *returnArr, uint8_t col) override {
                returnArr[i] = [112,114,116,118];
    };

    void show(FrontWord word) override {
        switch (word) {

        case FrontWord::es_ist:

**Comment by fs-sw** [comment]
Danke für eure Hilfe.
Es hat geklappt.
Ich musste bei der 7 Minuten Anzeige die Werte nur anpassen.
