### ISSUE TITLE
Keine WiFi Verbindung

### ISSUE THREAD

**Issue by DirkSchlecht** [ESPWortuhr/Multilayout-ESP-Wordclock#475]
Hallo. Ich habe einen NodeMCU V3 ESP8266-12F eingebaut und kann ihn auch über Visual Studio Code bespielen. Leider kommt als Startbildschirm der Uhr nur ein Herz und es geht nicht weiter. Es wird auch keine WiFi Verbindung hergestellt. In Visual Studio Code kommt folgende Meldung unter "Problems" : 'WiFiClient WiFiServer::available(uint8_t*)' is deprecated: Renamed to accept(). [-Wdeprecated-declarations].
Ich habe schon eine Uhr gebaut und der ESP8266 war ein anderer (NodeMCU V2). Der ist auch schmaler. Da funktioniert alles bestens. Habe auch schon mehrere Software Versionen probiert. Leider immer der gleiche Ablauf. Auch die BIN Datei direkt geflasht, mit keiner Änderung.

**Comment by Miklesoft** [comment]
Hallole, Dirk, hast Du eine Lösung gefunden??
