### ISSUE TITLE
Buchstaben Layout

### ISSUE THREAD

**Issue by J-Paul0815** [ESPWortuhr/Multilayout-ESP-Wordclock#476]
Bin gestern auf dieses Projekt gestoßen und bin schon sehr begeistert. Ich hoffe ich stelle meine Frage an richtiger Stelle, ein Forum oder Discord scheint es nicht zu geben. Bei mir ist das Buchstaben Layout anders, siehe Bild. Ich hatte ein Issue gefunden, in dem es hieß, dass man alternative Layouts hochladen kann, ich finde aber nicht was und wie. Hier das Layout:
![image](https://github.com/user-attachments/assets/b45feb17-a4a5-4b12-8555-e5d819c26693)
Wäre über jeden Hinweis sehr dankbar.

**Comment by dbambus** [comment]
Hallo @J-Paul0815 

auf der Website der Uhr kann man zwischen mehreren Layouts wählen. Dein Design entspricht dabei dem Layout `2clock`

andernfalls in der Config diese Zeile auskommentieren. 

```
// #define DEFAULT_LAYOUT Ger10x11Clock
```

Falls du weitere Hilfe braucht oder wirklich ein eigene Layout haben willst, dann nochmal melden. 

Mit freundlichen Grüßen
David

**Comment by J-Paul0815** [comment]
> Hallo @J-Paul0815
> 
> auf der Website der Uhr kann man zwischen mehreren Layouts wählen. Dein Design entspricht dabei dem Layout `2clock`
> 
danke @dbambus für die schnelle Antwort.
Wo finde ich ich die Auswahl vom Layout? Ich hatte mit der BIN Version 4.0.2 geflashed, fehlt mir da die "Experten" Einstellung?
LG Joerg

Nachtrag: Habe es doch gefunden: Nennt sich "10x11Uhr" Vielen Dank!
