### ISSUE TITLE
erster Start

### ISSUE THREAD

**Issue by DirkSchlecht** [ESPWortuhr/Multilayout-ESP-Wordclock#477]
Hallo. Kann mir bitte jemand helfen? Ich habe den ESP (NodeMCU V3 12F ESP8266) bespielt. Wenn die Uhr nun startet, kommt ein blaues Herz. Wie geht es jetzt weiter? Ist das irgendwo beschrieben? Wie kann ich auf den ESP zugreifen, um die Verbindungsdaten zur FB herzustellen?
Ich würde mich über jede Hilfe freuen
Vielen Dank
Grüße
Dirk

**Comment by DirkSchlecht** [comment]
Habs gefunden

**Comment by dbambus** [comment]
Ah super :-) 

Ja an einer Dokumentation sollte ich mal arbeiten
