### ISSUE TITLE
Uhr geht eine Minute nach

### ISSUE THREAD

**Issue by Miles-art** [ESPWortuhr/Multilayout-ESP-Wordclock#485]
Ich habe gerade die worldclock aufgesetzt. Kann es sein, dass die Minutenanzeige um eine Minute verzögert ist?
In der Weboberfläche ist es 13:20 aber die Uhr sagt "Viertel nach eins" und darunter habe ich 4 Punkte.

**Comment by dbambus** [comment]
Hallo @Miles-art,

evtl passt etwas mit der Zeitsync nicht mehr. Diese sollte sich aber zyklisch prüfen. 

Im Zweifelsfall kann man auch mal schauen, was die Serialausgabe denn anzeigt. Hier ist sekundengenau die Zeit der Uhr als Status gesendet. 

Mit freundlichen Grüßen
David

**Comment by dbambus** [comment]
Wenn das Problem weiter besteht, einfach melden. bis dahin schließe ich mal das Issue
