### ISSUE TITLE
Anzeigeoption "dreiviertel" nicht vorhanden

### ISSUE THREAD

**Issue by udo1toni** [ESPWortuhr/Multilayout-ESP-Wordclock#76]
Mit dem aktuellen Release 2.6.0 vom 24.03.2021 steht die Option für dreiviertel nicht zur Auswahl (Uhrenlayout Uhr 114)
![Screenshot 2021-03-24 125257](https://user-images.githubusercontent.com/5974344/112306314-f9965600-8c9f-11eb-8295-4519831918aa.png)

**Comment by dbambus** [comment]
Hallo @udo1toni, bei dem UHR_114 Layout ist auch kein dreiviertel in der Matrix vorhanden. Welches Layout verwenden Sie genau? Ist es für Sie möglich ein Bild zu machen ?

**Comment by udo1toni** [comment]
Ja, stimmt, das habe ich inzwischen auch festgestellt. Aber das Layout beinhaltet durchaus dreiviertel als Begriff, es ist lediglich nicht in der Matrix definiert. Ich habe inzwischen ein Update hochgeladen.

**Comment by dbambus** [comment]
In dem aktuellen `main` branch sollte der Support vollständig enthalten sein :-)
