### ISSUE TITLE
Structs ?

### ISSUE THREAD

**Issue by dbambus** [ESPWortuhr/Multilayout-ESP-Wordclock#79]
Hallo @ATho95 @tali , 

ich habe etwas in meinem Coding Styleguide für C++ reingeschaut und paar Ideen auf geschnappt. Was hält Ihr davon, wenn man die spezifischen Variablen vom Global Struct nochmals in einzelne Structs unterteilt. So könnte man den Speicherverbrauch im EEPROM reduzieren.

Ich habe hierzu mal einen Branch erstellt und ein paar Variablen mal gruppiert. https://github.com/dbambus/Wortuhr/commit/b60f69e3a2836ee78c5943097e99b72515bd47d3

Der Speicherverbrauch im RAM bleibt dabei gleich, im hinterlegten EEPROM wird er kleiner, aber der verbrauchte Programmspeicher steigt um 1 kB. Das kann ich mir bisher noch nicht erklären. 

Was gefällt euch besser ?

**Comment by tali** [comment]
Das `__attribute__((packed))` packt die Bytes näher zusammen, braucht dann aber bei allen Zugriffen extra Code um das wieder ein-/auszupacken. Vermutlich kommt da der erhöhte Programmspeicher her. Langsamer wird es dadurch vermutlich auch.
Ist denn der EEPROM Speicherverbrauch so kritisch?

Eine gängige Praxis ist auch, nur wirklich im persistenten Medium zu packen, das dann beim Booten einmal in den RAM zu entpacken und dort nur noch mit einer normalen Struktur zu arbeiten.

Abspeichern muss ja auch gar nicht unbedingt in eine gepackte Struktur geschehen. Ich bin im Augenblick eher geneigt, in die andere Richtung zu gehen: Konfiguration als JSON serialisieren und das abspeichern. Gerne auch in ein Dateisystem.
Das hätte auch den Vorteil, dass wir später leichter neue Variablen einführen können, ohne explizit verschiedene Versionen vom Speicherlayout unterstützen zu müssen.

**Comment by dbambus** [comment]
Hey, 

ja das mit JSON hatte ich mir auch schon überlegt. :-) Das mit dem Dateisystem ist aber eine schwierigere Angelegenheit, da man das nicht einfach in einer Binary auf ein bestehendes System bringen kann. Eine Möglichkeit wäre eine Art Textfeld auf eine Firstboot Page einzurichten und dort ein JSON einzufügen, das alle persistente Config enthält. Das war letztlich durch https://github.com/ESPWortuhr/Wortuhr/issues/27 gemeint.

Back to Topic. Speicherverbrauch im EEPROM ist nicht all zu wichtig, aber ein Faktor. Wenn ich mich recht erinnere gibt es ein Maximum für OTA Updates, was letztlich die möglichen neunen Features limitiert. Deshalb wollte ich mal schauen, was möglich wäre, um den bestehenden Code zu verbessern.
Mehr Bitweises Arbeiten habe ich da in den Vordergrund gestellt. :-) Da habe ich aber noch ein Paar Verbesserungsmöglichkeiten ^^

**Comment by ATho95** [comment]
Der "EEPROM" Bereich ist 4kB groß und liegt im oberen 16kB Bereich des Flashs und hat eine Granularität von 1kB. Die EEPROM Klasse cashed den Bereich, hier 512 Byte, auch schon im RAM, wo sich ein paar Byte sparen liessen. Wird Speicher knapp, könnte man sich auch aus diesem Cash bedienen (G = (struct GLOBAL) EEPROM.getConstDataPtr()) G->irgendwas ...
 aber ich sehe da keine Notwendigkeit.
Bei "packed" Strukturen werden die Variablen direkt aneinander gelegt, so dass keine Gaps entstehen aber 16 oder 32 Bit Variablen auf ungeraden Adressen landen können. Die CPU kann auf diese Werte nicht atomar zugreifen. Der Compiler bringt zusätzlichen Code rein, der Byteweise zugreift und die 16/32 Bit Variablen zusammensetzt.
Ein Filesystem schränkt die OTA Möglichkeiten da viel gravierender ein. Hätte aber auch den Charme, dass man die Webseiten da ablegen kann. Aber, wie dbambus schon sagte: Die Handhabung ist aufwändiger.

Um leichter neue Variablen einzuführen hatte ich vor Jahren dem Eisbär mal vorgeschlagen, den EEPROM Bereich mit zwei Variablen zu erweitern: MagicNumber & Size.
Wird die GLOBAL Struktur erweitert (nur möglich am Ende was anhängen) ändert sich auch die Size. Beim booten wird geguckt, ob die MagicNumber vorhanden ist und die Size im EEPROM und der Default Struktur gleich ist. Wenn ja: erklärt sich selber - wenn nein: Werden die Daten aus dem EEPROM über die Default Daten kopiert und mit neuer Size zurückgeschrieben.
