### ISSUE TITLE
Passwort für "Uhr" Wlan

### ISSUE THREAD

**Issue by Psychedili** [ESPWortuhr/Multilayout-ESP-Wordclock#98]
Hallo,
Ich würde das WLAN PW für die Version 2.5.0 benötigen.

**Comment by dbambus** [comment]
Hallo, 

das Passwort war im früheren Release "12345678"

**Comment by Psychedili** [comment]
Danke für die schnelle Antwort.
Jetzt habe ich noch eine Frage. Ich habe in der Version 2.5.0 das Uhrenlayout anpassen müssen.
Wenn ich jetzt die .bin Datei der Version für ein OTA Update benutze ist dann mein Uhrenlayout auch überschrieben oder bleibt das erhalten?

**Comment by dbambus** [comment]
Hallo @Psychedili,

Wenn du direkt die vorkompilierte Binary verwendest, wird das Uhren Layout, dass du in deinem Code damals angepasst hast, überschrieben werden. Diese Release-Binary ist für Neulinge gedacht, die ein fertiges Image wollen und ein standardmäßiges Layout verwenden. 

Du musst für dein spezielles Layout den frischen SourceCode von diesem Repo hernehmen und anschließend dein Layout in diesen Einpflegen, anschließend kompilieren und flashen. 

LG
David
